### ISSUE TITLE
Split out GVariant code into a separate library

### ISSUE THREAD

**Issue by robert-ancell** [canonical/gsettings.dart#10]
That can be shared with dbus.dart etc.

**Comment by aadarshadhakalg** [comment]
Hey @robert-ancell , can you share more details? I would love to work on this issue. Thanks

**Comment by robert-ancell** [comment]
The idea was to take the common gvariant code and put it into a separate library, but I haven't seen a great need for this. I'm going to close this issue as I think it would make things more complex and not bring any major benefits.
