### ISSUE TITLE
Add method to reset the value of a key

### ISSUE THREAD

**Issue by jpnurmi** [canonical/gsettings.dart#11]
In addition to #8, it would be nice to be able to reset settings.

**Comment by robert-ancell** [comment]
You can reset a value by setting its value to null in `GSettings.set()`. I considered a separate method call for this to be more explicit, but left it in `set()` as that allows you to set multiple values in one transaction without the more complex transaction code in the C implementation. I was considering if we should have a simple `set()` and `reset()` for the single case, and a `setMultiple()` for the less frequently required multiple case. WDYT?

**Comment by robert-ancell** [comment]
Or called `setAll()` which seems to match the Dart conventions more.

**Comment by jpnurmi** [comment]
> You can reset a value by setting its value to null in `GSettings.set()`.

Oh, I missed that. And it was even documented. :)

> I was considering if we should have a simple `set()` and `reset()` for the single case, and a `setMultiple()` for the less frequently required multiple case. WDYT?
>
> Or called `setAll()` which seems to match the Dart conventions more.

Sounds nice to make it more convenient. The settings app is also setting only singular values so far.
