### ISSUE TITLE
Support GSETTINGS_BACKEND env variable

### ISSUE THREAD

**Issue by robert-ancell** [canonical/gsettings.dart#13]
GSettings actually has multiple backends. We should support that, even if we just throw an exception for backends we don't support.

**Comment by jpnurmi** [comment]
I pushed a quick and dirty prototype here: https://github.com/jpnurmi/gsettings.dart/commits/keyfile

NOTE: This is only able to read string arrays that are needed for shortcuts in Workshops. `GVariantTextCodec` is missing support for variant type ('v') values. I don't know what to do about writing, whether there's a way to instruct `ca.desrt.dconf.Writer` to use a keyfile or if we need to write it ourselves...

**Comment by robert-ancell** [comment]
When you use the keyfile backend DConf is not used at all - you just read/write the keyfile directly.

**Comment by robert-ancell** [comment]
I'm currently working on getting glib aware if you are running in a snap and automatically using the keyfile backend if you don't have gsettings access (the same behaviour as flatpak). We'll want the same behaviour in gsettings.dart.

**Comment by robert-ancell** [comment]
Supported now with memory and keyfile backends.
