### ISSUE TITLE
Support relocatable schemas

### ISSUE THREAD

**Issue by jpnurmi** [canonical/gsettings.dart#20]
For example:
```
$ gsettings get org.gnome.desktop.notifications.application:/org/gnome/desktop/notifications/application/org-gnome-terminal/ application-id
'org.gnome.Terminal.desktop'
```

**Comment by robert-ancell** [comment]
This only applies to "relocatable schemas", right?

**Comment by jpnurmi** [comment]
I'm not an expert but gsettings help suggests so. :slightly_smiling_face: 

> PATH      The path, for relocatable schemas

> Specifying the path is only needed if the schema does not have a fixed path.
