### ISSUE TITLE
Using gsettings.dart seems to require libgtk-3-dev to be installed

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/gsettings.dart#22]
It seems like libgtk-3-dev is needed to be installed to run a binary from the linux build/bundle which uses gsettings.dart. Otherwise the window is not fully loaded and the application moans about a missing shared object libgio-2.0.so

@kenvandine had the idea that this might be an issue with gsettings.dart
Thus I am opening the issue here

CC @jpnurmi @robert-ancell 

Ref https://github.com/Feichtmeier/settings/issues/182

**Comment by kenvandine** [comment]
I suspect it's something with libffi usage in gsettings.dart, it should be loading the versioned so.

**Comment by jpnurmi** [comment]
The ideal solution would be to port the settings app to the new D-Bus based gsettings.dart. The old FFI-based gsettings.dart actually never was in this repo. :slightly_smiling_face:

**Comment by Feichtmeier** [comment]
Oh... Then sorry for the noise.
Will test out the new version and report back

**Comment by Feichtmeier** [comment]
Fixed ! Thank you very much!
