### ISSUE TITLE
Adding support to specify schema directory

### ISSUE THREAD

**Issue by domferr** [canonical/gsettings.dart#55]
Currently, there is no direct option to specify a directory to search for schemas. Instead, the library relies solely on the `GSETTINGS_SCHEMA_DIR` environment variable. While this approach can be sufficient in some cases, it may limit the flexibility and usability of the library in certain scenarios. 
On the other hand, the command-line interface allows this functionality by utilizing the --schemadir flag.

As a user of this library library, I believe it would greatly improve its functionality if it provided a way to specify a schema directory as a parameter when initializing or using the library. This would allow developers to programmatically define the location of the schemas, providing more control and flexibility in their applications.

Given my interest in this matter, I would like to offer my assistance and contribute to the project in implementing this enhancement. I am open to collaborating with the project maintainers to help address this issue and provide a solution that benefits the wider user community. Any guidance, hints, or advice on how to approach this enhancement would be highly appreciated.

Thank you for your time and consideration. I look forward to hearing your thoughts on this matter and discussing potential next steps.

**Comment by robert-ancell** [comment]
Yes, this seems like a good idea, I'd expect to do a similar things for the backend, i.e.
```dart
GSettings(this.schemaName,
      {this.path,
      DBusClient? systemBus,
      DBusClient? sessionBus,
      GSettingsBackend? backend,
      List<String>? schemaDirs})
```
i.e. only use the env variable if `schemaDirs` is null.
